general.import = [ "~/.config/alacritty/gruvbox-dark-hard.toml" ]

[window]
# Set the dimensions of the window, columns and lines can be set to 0 for default
dimensions = { columns = 0, lines = 0 }
padding = { x = 0, y = 0 }
resize_increments = true
dynamic_padding = true 
decorations = "None"
opacity = 0.9

[terminal]
shell ="/usr/bin/fish"

[keyboard]
bindings = [
  { key = "Return", mods = "Control", action = "SpawnNewInstance" }
]

[font]
# Font settings
size = 11.0
offset = { x = 0, y = 0 }

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"
