[window]
# Set the dimensions of the window, columns and lines can be set to 0 for default
dimensions = { columns = 0, lines = 0 }
padding = { x = 0, y = 0 }
resize_increments = true
dynamic_padding = true 
decorations = "None"
opacity = 0.9

[terminal]
shell ="/usr/bin/fish"

[keyboard]
bindings = [
  { key = "Return", mods = "Control", action = "SpawnNewInstance" }
]

[font]
# Font settings
size = 11.0
offset = { x = 0, y = 0 }

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[colors]
# Colors settings
[colors.normal]
green = "#1ba63f"
red = "#e25d56"
yellow = "#e9bf57"
blue = "#4a88e4"
magenta = "#915caf"
cyan = "#23acdd"
white = "#f0f0f0"
black = "#0E1415"

[colors.primary]
background = "#0E1415"
foreground = "#CECECE"


[colors.bright]
green = "#88db3f"
red = "#f36868"
yellow = "#f0bf7a"
blue = "#6f8fdb"
magenta = "#e987e9"
cyan = "#4ac9e2"
white = "#FFFFFF"
black = "#777777"
