
[window]
  dimensions = { columns = 0, lines = 0}
  padding = { x = 0, y = 0}
  dynamic_padding = false # it ajust's padding dynamicly  
  decorations = "None" # no decoration 
  opacity = 0.9
  startup_mode = "Windowed" 


[font]
  size =  10.999

  [font.normal]
  family = "JetBrainsMono Nerd Font"
  style = "Bold"

  [font.bold]
  family = "JetBrainsMono Nerd Font"
  style = "Bold"

  [font.italic]
  family = "JetBrainsMono Nerd Font"
  style = "Italic"

  [font.bold_italic]
  family = "JetBrainsMono Nerd Font"
  style = "Bold Italic"

[colors]
  normal = {green = "#1ba63f"}

[general]
import = [
    "~/.config/alacritty/themes/themes/alabaster_dark.toml"
	#"~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
]
